const cancelActionTypes = {
  CANCEL_ORDER_REQUEST: 'CANCEL_ORDER_REQUEST',
  CANCEL_ORDER_SUCCESS: 'CANCEL_ORDER_SUCCESS',
  CANCEL_ORDER_FAIL: 'CANCEL_ORDER_FAIL',
  CANCEL_ORDER_STATUS_CLEAR: 'CANCEL_ORDER_STATUS_CLEAR',
};

export default cancelActionTypes;
