const orderActionTypes = {
  OPEN_ORDER_REQUEST: 'OPEN_ORDER_REQUEST',
  OPEN_ORDER_SUCCESS: 'OPEN_ORDER_SUCCESS',
  OPEN_ORDER_FAIL: 'OPEN_ORDER_FAIL',

  EX_RATE_REQUEST: 'EX_RATE_REQUEST',
  EX_RATE_SUCCESS: 'EX_RATE_SUCCESS',
  EX_RATE_FAIL: 'EX_RATE_FAIL',

  ORDER_TOKEN_REQUEST: 'ORDER_TOKEN_REQUEST',
  ORDER_TOKEN_SUCCESS: 'ORDER_TOKEN_SUCCESS',
  ORDER_TOKEN_FAIL: 'ORDER_TOKEN_FAIL',
};

export default orderActionTypes;
